spring:
  application:
    name: hydros-sso-demo-client

server:
  port: 9091
  servlet:
    session:
      cookie:
        name: HYDROS_DEMO_SID

demo:
  sso:
    issuer: http://localhost:7071
    client-id: demo-client
    client-private-key-path: classpath:keys/demo-client-private.pem
    redirect-uri: http://localhost:9091/callback
    scope: openid profile
